---
name: go test
on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
jobs:
  gotest:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v2
    - name: download the required packages
      run: go mod download
    - run: go test --cover --race -v ./...
      